# For more information: https://laravel.com/docs/sail
version: "3"
services:
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "laracast"
      MYSQL_USER: "laracast"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "mysql:/var/lib/mysql"
volumes:
  mysql:
    driver: local
